### ISSUE TITLE
Where can I get the weights for training data?

### ISSUE THREAD

**Issue by aithlab** [quantumiracle/UPESI#2]
Thanks for sharing the code.
I tried to run the code by following the procedure in README.
In the phase of downloading the training data, I think the weights should be needed, 
but I couldn't find the file or related link.
Could you share the weights for getting training data?

**Comment by quantumiracle** [comment]
Right, I didn't upload the weights in the repo here, considering the minimal size of the repo would be good.
The weights of the model for collecting the training data can be easily acquired, through running the following:
```
python train.py --train --env inverteddoublependulum --process 1 --alg td3
```
as an example for the InvertedDoublePendulum environment. After training, there will be weights in the data folder. You just need to replace the path [here](https://github.com/quantumiracle/UPESI/blob/76f8fc1e7530f3e0001c8c764805b109bb4ceff2/dynamics_predict/train_dynamics.py#L440) with the one you got to make `train_dynamics.py` run.

I will update these in readme.

**Comment by aithlab** [comment]
Thanks for your help.

I followed the running you advised, then it occurred error as follows:

`ModuleNotFoundError: No module named 'default_params'`

I think that the "default_params.py" is needed to load the parameters such as learning rates, hidden dimensions of neural networks, etc.
I found a similar module defaults.py in the "dynamics_predict" folder, but it does not include the parameters.

Could you share the default_params.py file or the information about the training parameters?

**Comment by quantumiracle** [comment]
Hi, 

Thanks for pointing out. I just update the repo with two parameter files uploaded. 
Feel free to raise issue here if you spot any other problem. I will answer as soon as possible.
